### ISSUE TITLE
multipcf -> doMultiPCF fails

### ISSUE THREAD

**Issue by nurmians** [ShixiangWang/copynumber#2]
multipcf -> doMultiPCF fails with

`Error in Sum[, 1:n] : subscript out of bounds`

when nProbes is 1. Maybe add a check somewhere to handle this situation?

**Comment by ShixiangWang** [comment]
Hello @nurmians, I saw an update version at https://github.com/igordot/copynumber/, could you try it and let it know if the issue still exists? If yes, I will try to debug the code, hope you can provide a minimal dataset to reproduce this issue.

**Comment by nurmians** [comment]
Thanks for the fast reply

```df <- data.frame( Chromosome=c(19,19,19,19,19), Position= c(24907774,27242936,27243091,27243657,27243733), sample1=c(0.4444444,0.5609756,0.5405405,0.3658537,0.3414634), sample2=c(0.5166667,0.6140351,0.5614035,0.5283019,0.6034483), sample3=c(0.4166667,0.5102041,0.4918033,0.5000000,0.4354839))```

```
winsorized = copynumber::winsorize(data = df)
copynumber::multipcf(data = winsorized, Y = df, fast = T, gamma = 0.45, return.est = T, normalize = F)   
```   
Error in Sum[, 1:n] : subscript out of bounds

This is a rare event that happens when there is only one datapoint on the other arm I think. Here is my "hotfix" for the issue.

```
  copynumber::multipcf

    #Check sd; cannot normalize if sd=0 or if sd=NA:
    if(any(sd==0) || any(is.na(sd)) || nrow(arm.data) == 1 ){
      if ( nrow(arm.data) == 1) { 
        print("nProbes == 1 FIX!")  
      }
 ...

    segments <- rbind(segments,segments.c)
    if(return.est){
      # Can't tell if yhat needs to be transposed in every scenario
      # so do it if dimensions do not match
      if( ncol(yhat) == ncol(mpcf.est) ) {
        yhat = t(yhat)
      }
      mpcf.est <- rbind(mpcf.est,t(yhat))
    } 
```

**Comment by ShixiangWang** [comment]
@nurmians It did work, thanks for your contribution :).
