### ISSUE TITLE
First 2 probes on chromosome arm can return suspect results when kmin=1

### ISSUE THREAD

**Issue by p-priestley** [ShixiangWang/copynumber#3]
Hello - just noticed this small issue.

Here is a simple example:

**INPUT**
$ cat test2.tsv
chromosome	position	CN
X	1000	2
X	2000	4
X	3000	0.5
X	4000	1

**CODE**
library(copynumber)
baf <- read.table("~/hmf/analyses/panel/test2.tsv", header=TRUE, stringsAsFactors = T)
baf.seg<-pcf(baf,verbose=FALSE,gamma=100,kmin=1)
baf.seg

**OUTPUT**
  sampleID chrom arm start.pos end.pos n.probes  mean
1       CN     X   p      1000    1000        1  8.00
2       CN     X   p      2000    2000        1 10.00
3       CN     X   p      3000    4000        2  0.75

You can see the mean in both regions is ABOVE the max probe value in the region.

**Comment by ShixiangWang** [comment]
Hi @p-priestley, Thanks for your question. However, I am not the developer of copynumber. This repo is the fork of copynumber package with hg38 support.

For your question, I would recommend you use the bioconductor support site or debug the code to see how the result is generated with `debug()` function.

Best,

Shixiang

**Comment by p-priestley** [comment]
Thanks.  Sorry.  My mistake
