### ISSUE TITLE
Sequenza preprocessing

### ISSUE THREAD

**Issue by Jiayi-Wang-Joey** [ShixiangWang/copynumber#4]
Hi Shixiang,

I have the issue of running sequenza with hg38. The copynumber package works fine, but do you have a problem with sequenza-utils preprocessing?
After preprocessing, the seqz.gz file only contains information about chr1, chr10 and chr11 by using hg38. If I do preprocess using hg19.fa, the output works fine. How do you solve this problem?

Kind regards,
Jiayi

**Comment by HushWay** [comment]
> 

The problem may be caused by the chromosome order, natural order is 1, 2, .... while alphabetical order is chr1, chr10, ... .When they are mixed, only chr1, chr10... can be correctly matched.

**Comment by ShixiangWang** [comment]
> The problem may be caused by the chromosome order, natural order is 1, 2, .... while alphabetical order is chr1, chr10, ... .When they are mixed, only chr1, chr10... can be correctly matched.

Great，thanks for the answer。
